##  Importing the packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel('EMR analysis online.xlsx')

In [3]:
df = pd.DataFrame(data)
df.head()

,S.NO,Submitted Time,1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS,2. SEX,3. LEVEL OF EDUCATION,4. Profession,5. Name of clinic,6. SECTION TWO : TECHNICAL FACTORS,7. what is Database version,8. Is EMR online /offline,...,31. Does your facility have a regular meetings to improve the EMR utilization?,32. Have you received regular feedback on your report ?,"33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n",34. facility staff complete EMR tasks in a timely manners (i.e meet deadlines ),"35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data","36. SECTION FOUR : BEHAVIOURAL FACTOR\n PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE",37. collecting data is meaningful/useful work for me,38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties,39. collecting information gives me the feeling that data is needed for monitoring facility performance,40. my work of collecting data is appreciated and valued by superiors
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [4]:
df.shape

(79, 42)

In [5]:
df.head()

,S.NO,Submitted Time,1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS,2. SEX,3. LEVEL OF EDUCATION,4. Profession,5. Name of clinic,6. SECTION TWO : TECHNICAL FACTORS,7. what is Database version,8. Is EMR online /offline,...,31. Does your facility have a regular meetings to improve the EMR utilization?,32. Have you received regular feedback on your report ?,"33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n",34. facility staff complete EMR tasks in a timely manners (i.e meet deadlines ),"35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data","36. SECTION FOUR : BEHAVIOURAL FACTOR\n PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE",37. collecting data is meaningful/useful work for me,38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties,39. collecting information gives me the feeling that data is needed for monitoring facility performance,40. my work of collecting data is appreciated and valued by superiors
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [6]:
df.columns

Index(['S.NO', 'Submitted Time',
       '1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS ', '2. SEX ',
       '3. LEVEL OF EDUCATION ', '4. Profession', '5. Name of clinic ',
       '6. SECTION TWO : TECHNICAL FACTORS ', '7. what is Database version  ',
       '8. Is EMR  online /offline ',
       '9. Is network connectivity a challenge?',
       '10. if yes ,what alternative do you have when there is no power ',
       '11. Is there a designated person to enter patient data upon registration in the health facility?',
       '12. How are patient registered upon arrival at the health facility?',
       '13. is there a designated person to compile EHIS reports ?\n',
       '14. Do you take orientation on the EMR   utilization upon employment?',
       '15. have you attended training on the Health Patient Registration System (HPRS) in the last 12 months ?',
       '16. if your answer is yes for question number 15 ,which topic did you train ?',
       '17. if your answer is yes for question number 15,who provides the training?',
       '18.          How do you classify/rate the EMR  software based on your experience ',
       '19. The following questions refer to the             computer/s used for EMR .\n\nHow long does it take to get technical support after an assistant call is logged ?',
       '20. For the following questions please express your level of agreement using the likert scale;',
       '21. For the following questions please express your level of agreement using the likert scale;',
       '22. I think that I need the support of a technical person to be able to use the system ',
       '23. I found the various functions of the system to be well integrated ',
       '24. I felt  very confident using the system ',
       '25. SECTION THREE: ORGANISATIONAL FACTOR ',
       '26. Do you have the capacity to make decisions relating to your responsibility ',
       '27. which organizational factor/s influence information use in your facility (You can choose more than one answer)',
       '28. does your facility have regular monitoring and evaluation supervisor for EMR ?',
       '29. Does the facility have well streamline health information policies ',
       '30. does the facility have an action plan for EMR  ?',
       '31. Does your facility have a regular meetings to improve the EMR utilization?',
       '32. Have you received regular feedback on your report ?',
       '33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n  ',
       '34. facility staff complete EMR  tasks in a timely manners (i.e meet deadlines )',
       '35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data ',
       '36. SECTION FOUR : BEHAVIOURAL FACTOR\n   PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE',
       '37. collecting data is meaningful/useful work for me ',
       '38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties ',
       '39. collecting information gives me the feeling that data is needed for monitoring facility performance ',
       '40. my work of collecting data is appreciated and valued by superiors '],
      dtype='object')

In [7]:
# Mapping for new column names

mapping = {
    'S.NO': 'S/N',
    'Submitted Time' : 'time',
    '1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS ':'Age',
    '2. SEX ' : 'sex',
    '3. LEVEL OF EDUCATION ': 'education',
    '4. Profession': 'profesion',
    '5. Name of clinic ': 'clinic_name/department',
    '6. SECTION TWO : TECHNICAL FACTORS ': 'EMR_designated_computer',
    '7. what is Database version  ' : 'database_version',
    '8. Is EMR  online /offline ': 'emr_online_offline',
    '9. Is network connectivity a challenge?': 'network_connectivity_challenge',
    '10. if yes ,what alternative do you have when there is no power ': 'alternative_power_outage',
    '11. Is there a designated person to enter patient data upon registration in the health facility?': 'designated_person_patient_data',
    '12. How are patient registered upon arrival at the health facility?': 'patient_registration_method',
    '13. is there a designated person to compile EHIS reports ?': 'designated_person_ehis_reports', 
    '14. Do you take orientation on the EMR   utilization upon employment?': 'orientation_emr_utilization',
    '15. have you attended training on the Health Patient Registration System (HPRS) in the last 12 months ?': 'hprs_training_last_12_months',
    '16. if your answer is yes for question number 15 ,which topic did you train ?': 'hprs_training_topic',
    '17. if your answer is yes for question number 15,who provides the training?': 'hprs_training_provider',
    '18.          How do you classify/rate the EMR  software based on your experience ': 'emr_software_rating',
    '19. The following questions refer to the             computer/s used for EMR .\n\nHow long does it take to get technical support after an assistant call is logged ?': 'technical_support_time',
    '20. For the following questions please express your level of agreement using the likert scale;': 'likely to use_emr',
    '21. For the following questions please express your level of agreement using the likert scale;': 'emr_is_complex',
    '22. I think that I need the support of a technical person to be able to use the system ': 'need_technical_support',
    '23. I found the various functions of the system to be well integrated ': 'good_system_functions_integration',
    '24. I felt  very confident using the system ': 'confidence_using_system',
    '25. SECTION THREE: ORGANISATIONAL FACTOR ': 'used_emr_decision_making',
    '26. Do you have the capacity to make decisions relating to your responsibility ': 'capacity_decision_making',
    '27. which organizational factor/s influence information use in your facility (You can choose more than one answer)': 'organisational_factors_influence',
    '28. does your facility have regular monitoring and evaluation supervisor for EMR ?': 'regular_monitoring_evaluation_supervisor',
    '29. Does the facility have well streamline health information policies ': 'health_information_policies',
    '30. does the facility have an action plan for EMR  ?': 'action_plan_emr',
    '31. Does your facility have a regular meetings to improve the EMR utilization?': 'regular_meetings_emr_utilization',
    '32. Have you received regular feedback on your report ?': 'regular_feedback_report',
    '33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n  ': 'emr_performance_monitoring',
    '34. facility staff complete EMR  tasks in a timely manners (i.e meet deadlines )': 'timely_completion_emr_tasks',
    '35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data ': 'commitment_emr_mission',
    '36. SECTION FOUR : BEHAVIOURAL FACTOR\n   PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE': 'tediousness_emr_data_collection',
    '37. collecting data is meaningful/useful work for me ': 'meaningful_data_collection',
    '38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties ': 'data_collection_burden',
    '39. collecting information gives me the feeling that data is needed for monitoring facility performance ': 'data_collection_monitoring',
    '40. my work of collecting data is appreciated and valued by superiors ': 'data_collection_appreciation'
}
# Renaming columns using the mapping

In [8]:
df.rename(columns=mapping, inplace=True)
# Display the first few rows of the updated DataFrame

In [9]:
df.head()

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [10]:
df.iloc[:5:,:25]

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,orientation_emr_utilization,hprs_training_last_12_months,hprs_training_topic,hprs_training_provider,emr_software_rating,technical_support_time,likely to use_emr,emr_is_complex,need_technical_support,good_system_functions_integration
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,No,None (others),Nil (others),Easy to use,within 24 hours,Agree,Strongly Disagree,strongly disagree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,No | Yes,Data entry,Unit/Department head,Easy to use,within 24 hours,strongly disagree,Disagree,Strongly Agree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,No,Yes,Data entry,EHIS focal person,Easy to use,within 24 hours,strongly Agree,Strongly Disagree,strongly disagree,agree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,No,other please specify,EHIS focal person,Easy to use,within 24 hours,strongly Agree,Strongly Disagree,Disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,Yes,Data Analysis,Unit/Department head,Easy to use,within 24 hours,strongly disagree,Strongly Disagree,Neither Agree or Disagree,strongly agree

In [11]:
df.iloc[:5:,25:]

,confidence_using_system,used_emr_decision_making,capacity_decision_making,organisational_factors_influence,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,strongly Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,Agree,no,yes,Organizational rules *( No Answer )\nfinancia...,yes,yes,yes,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,strongly Agree,no,no,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,strongly Disagree,yes,yes,Organizational rules *( No Answer )\nfinancia...,yes,yes,yes,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [12]:
df.columns

Index(['S/N', 'time', 'Age', 'sex', 'education', 'profesion',
       'clinic_name/department', 'EMR_designated_computer', 'database_version',
       'emr_online_offline', 'network_connectivity_challenge',
       'alternative_power_outage', 'designated_person_patient_data',
       'patient_registration_method',
       '13. is there a designated person to compile EHIS reports ?\n',
       'orientation_emr_utilization', 'hprs_training_last_12_months',
       'hprs_training_topic', 'hprs_training_provider', 'emr_software_rating',
       'technical_support_time', 'likely to use_emr', 'emr_is_complex',
       'need_technical_support', 'good_system_functions_integration',
       'confidence_using_system', 'used_emr_decision_making',
       'capacity_decision_making', 'organisational_factors_influence',
       'regular_monitoring_evaluation_supervisor',
       'health_information_policies', 'action_plan_emr',
       'regular_meetings_emr_utilization', 'regular_feedback_report',
       'emr_performance_monitoring', 'timely_completion_emr_tasks',
       'commitment_emr_mission', 'tediousness_emr_data_collection',
       'meaningful_data_collection', 'data_collection_burden',
       'data_collection_monitoring', 'data_collection_appreciation'],
      dtype='object')

In [13]:
# saving the updated DataFrame to a new Excel file
#df.to_excel('EMR_analysis_online_updated.xlsx', index=False)

# Loading the offline data file to preview and preprocess it

In [14]:
data_2 = pd.read_excel('EMR analysis offline.xlsx')
df_2 = pd.DataFrame(data_2)

In [15]:
df.shape

(79, 42)

In [16]:
df_2.shape

(90, 45)

In [17]:
df_2.head()

,Timestamp,Age,Sex,Level of Education,Profession,Name of Clinic or Department,Does facility have a working computer/s designated for EMR,What is the database version,Is EMR online/offline,Is network connectivity a challenge,...,Does your facility have regular meetings to improve the EMR,Have you received regular feedback on your report?,Health department superiors use EMR data for service performance monitoring and target setting.,"Facility staff complete EMR tasks in a timely manner (i.e., meet deadlines)","Facility staff display commitment to the EMR mission (i.e., to generate and use good quality- accurate, complete, and timely-data.)","I find collecting/recording data to be tedious (i.e., repetitive or duplicative",Collecting data is meaningful/useful work for me,"I feel the data I collect burdens my workload, making it difficult for me to complete my other duties",Collecting information gives me the feeling that data is needed for monitoring facility performance,My work of collecting data is appreciated and valued by superiors
0,2025-08-21 22:09:23.948,25,Female,Degree,Doctor,O&G,NaN,EMR,Online,Always,...,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0
1,2025-08-21 22:12:37.611,23,Female,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,...,No,No,3.0,3.0,3.0,2.0,4.0,3.0,3.0,3.0
2,2025-08-21 22:15:26.993,37,Female,Postgraduate,Doctor,Family Medicine,Yes,NaN,Online,Most of the time,...,No,Yes,3.0,3.0,3.0,NaN,3.0,3.0,3.0,3.0
3,2025-08-21 22:18:44.464,25,Male,Postgraduate,Doctor,O&G,Yes,NaN,Offline,Sometimes,...,Yes,Yes,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0
4,2025-08-21 22:21:01.081,26,Male,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,...,No,No,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0

In [18]:
df_2.columns.tolist()

['Timestamp',
 'Age',
 'Sex',
 'Level of Education',
 'Profession',
 'Name of Clinic or Department ',
 'Does facility have a working computer/s designated for EMR',
 'What is the database version',
 'Is EMR online/offline ',
 'Is network connectivity a challenge ',
 'If yes, what alternatives do you use when there is no power',
 'Is there a designated person to enter patients data upon registration in health',
 'How are patients registered upon arrival at the health facility ',
 'Is there a designated person to compile EMR reports? ',
 'Do you take orientation on the EMR utilization upon employment?',
 'Have you attended training on the Health Patient Registration System (HPRS) in the last 12 months?',
 'If your answer is yes for 15, in which topic did you train?\n(You can choose more than one answer)',
 'If your answer is yes for 15, in who provides the training?\n(You can choose more than one answer)',
 'How do you classify/rate the EMR software based on your experience?',
 'How long does it take to get technical support after an assistance call is logged?',
 'I think I would like to use EMR more frequently',
 'I find the system unnecessarily complex',
 'I think I need the support of a technical person to be able to use the system',
 'I found the various functional system to be well integrated',
 'I felt very confident using the system',
 'Have you used EMR for decision making at your facility',
 'Do you have the capacity to make decisions relating to your responsibility?',
 'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Organizational rules]',
 'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Financial resources]',
 'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Organizational practice]',
 'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Inadequate human resource]',
 'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Poor leadership]',
 'Does your facility have regular monitoring and evaluation supervision for EMR',
 'Does your facility have well streamlined health information policies',
 'Does the facility have an action plan for EMR',
 'Does your facility have regular meetings to improve the EMR ',
 'Have you received regular feedback on your report?',
 'Health department superiors use EMR data for service performance monitoring and target setting.',
 'Facility staff complete EMR tasks in a timely manner (i.e., meet deadlines)',
 'Facility staff display commitment to the EMR mission (i.e., to generate and use good quality- accurate, complete, and timely-data.)',
 'I find collecting/recording data to be tedious (i.e., repetitive or duplicative',
 'Collecting data is meaningful/useful work for me',
 'I feel the data I collect burdens my workload, making it difficult for me to complete my other duties',
 'Collecting information gives me the feeling that data is needed for monitoring facility performance',
 'My work of collecting data is appreciated and valued by superiors']

In [19]:
# creating the second mapping 

# Mapping for new column names

mapping2 = {
    'Timestamp': 'time',
    'Age': 'Age',
    'Sex': 'sex',
    'Level of Education': 'education',
    'Profession': 'profesion',
    'Name of Clinic or Department ': 'clinic_name/department',
    'Does facility have a working computer/s designated for EMR': 'EMR_designated_computer',
    'What is the database version': 'database_version',
    'Is EMR online/offline ': 'emr_online_offline',
    'Is network connectivity a challenge ': 'network_connectivity_challenge',
    'If yes, what alternatives do you use when there is no power': 'alternative_power_outage',
    'Is there a designated person to enter patients data upon registration in health': 'designated_person_patient_data',
    'How are patients registered upon arrival at the health facility ': 'patient_registration_method',
    'Is there a designated person to compile EMR reports? ': 'designated_person_patient_data',
    'Do you take orientation on the EMR utilization upon employment?': 'orientation_emr_utilization',
    'Have you attended training on the Health Patient Registration System (HPRS) in the last 12 months?': 'hprs_training_last_12_months',
    'If your answer is yes for 15, in which topic did you train?\n(You can choose more than one answer)': 'hprs_training_topic',
    'If your answer is yes for 15, in who provides the training?\n(You can choose more than one answer)': 'hprs_training_provider',
    'How do you classify/rate the EMR software based on your experience?': 'emr_software_rating',
    'How long does it take to get technical support after an assistance call is logged?': 'technical_support_time',
    'I think I would like to use EMR more frequently': 'likely to use_emr',
    'I find the system unnecessarily complex': 'emr_is_complex',
    'I think I need the support of a technical person to be able to use the system': 'need_technical_support',
    'I found the various functional system to be well integrated': 'good_system_functions_integration',
    'I felt very confident using the system': 'confidence_using_system',
    'Have you used EMR for decision making at your facility': 'used_emr_decision_making',
    'Do you have the capacity to make decisions relating to your responsibility?': 'capacity_decision_making',
    'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Organizational rules]' : 'Organizational rules',
    'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Financial resources]': 'financial resources',
    'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Organizational practice]': 'organizational practices',
    'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Inadequate human resource]': 'inadequate human resources',
    'Which organizational factor/s influence information use in your facility? (You can choose more than one answer) [Poor leadership]': 'poor leadership',
    'Does your facility have regular monitoring and evaluation supervision for EMR': 'regular_monitoring_evaluation_supervisor',
    'Does your facility have well streamlined health information policies': 'health_information_policies',
    'Does the facility have an action plan for EMR': 'action_plan_emr',
    'Does your facility have regular meetings to improve the EMR ': 'regular_meetings_emr_utilization',
    'Have you received regular feedback on your report?': 'regular_feedback_report',
    'Health department superiors use EMR data for service performance monitoring and target setting.': 'emr_performance_monitoring',
    'Facility staff complete EMR tasks in a timely manner (i.e., meet deadlines)': 'timely_completion_emr_tasks',
    'Facility staff display commitment to the EMR mission (i.e., to generate and use good quality- accurate, complete, and timely-data.)': 'commitment_emr_mission',
    'I find collecting/recording data to be tedious (i.e., repetitive or duplicative': 'tediousness_emr_data_collection',
    'Collecting data is meaningful/useful work for me': 'meaningful_data_collection',
    'I feel the data I collect burdens my workload, making it difficult for me to complete my other duties': 'data_collection_burden',
    'Collecting information gives me the feeling that data is needed for monitoring facility performance': 'data_collection_monitoring',
    'My work of collecting data is appreciated and valued by superiors': 'data_collection_appreciation'
}
# Renaming columns using the mapping

In [20]:
# renaming the colums in the 2nd file too
df_2.rename(columns=mapping2, inplace=True)

In [21]:
# previewing the first few rows of the updated DataFrame
df_2.iloc[:5,:15]

,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,network_connectivity_challenge,alternative_power_outage,designated_person_patient_data,patient_registration_method,designated_person_patient_data,orientation_emr_utilization
0,2025-08-21 22:09:23.948,25,Female,Degree,Doctor,O&G,NaN,EMR,Online,Always,Generator,Yes,Both,No,No
1,2025-08-21 22:12:37.611,23,Female,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,Generator,Yes,Both,Yes,No
2,2025-08-21 22:15:26.993,37,Female,Postgraduate,Doctor,Family Medicine,Yes,NaN,Online,Most of the time,Paper generating register,No,EMR,No,No
3,2025-08-21 22:18:44.464,25,Male,Postgraduate,Doctor,O&G,Yes,NaN,Offline,Sometimes,UPS,Yes,EMR,Yes,Yes
4,2025-08-21 22:21:01.081,26,Male,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,Paper generating register,No,EMR,No,No

In [22]:
df_2.iloc[:5,26:]

,capacity_decision_making,Organizational rules,financial resources,organizational practices,inadequate human resources,poor leadership,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,Yes,Yes,Yes,Yes,No,No,No,Yes,No,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0
1,Yes,No,No,Yes,No,No,No,No,No,No,No,3.0,3.0,3.0,2.0,4.0,3.0,3.0,3.0
2,No,No,Yes,No,Yes,No,No,Yes,No,No,Yes,3.0,3.0,3.0,NaN,3.0,3.0,3.0,3.0
3,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,Yes,Yes,Yes,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0
4,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0

In [23]:
df.iloc[:5,26:]

,used_emr_decision_making,capacity_decision_making,organisational_factors_influence,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,yes,yes,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,yes,yes,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,no,yes,Organizational rules *( No Answer )\nfinancia...,yes,yes,yes,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,no,no,Organizational rules *( yes )\nfinancial res...,yes,yes,yes,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,yes,yes,Organizational rules *( No Answer )\nfinancia...,yes,yes,yes,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

# Understanding the logic to split the organization_factors column in the online df

In [24]:
#checking the value type
org_factors = df['organisational_factors_influence'][0]
org_factors

'Organizational rules  *( yes  )\nfinancial resources  *( yes  )\norganizational practices  *( yes  )\ninadequate human resources  *( No Answer )'

In [25]:
# Splitting the string into a list of factors
org_factors_list = org_factors.split('\n')
org_factors_list

['Organizational rules  *( yes  )',
 'financial resources  *( yes  )',
 'organizational practices  *( yes  )',
 'inadequate human resources  *( No Answer )']

In [26]:
dictionary = {}
for factor in org_factors_list:
    splits = factor.split('*')
    dictionary[splits[0].strip()] = splits[1].replace('(', '').replace(')', '').strip()
dictionary

{'Organizational rules': 'yes',
 'financial resources': 'yes',
 'organizational practices': 'yes',
 'inadequate human resources': 'No Answer'}

# Defining the function to create the new columns for the online form df

In [27]:
# defining a function to map the factors 
def new_columns():
    dictionary = {}
    for i in range(len(df['organisational_factors_influence'])):
        org_factors = df['organisational_factors_influence'][i]
        org_factors_list = org_factors.split('\n')
        for factor in org_factors_list:
            splits = factor.split('*')
            if splits[0].strip() in dictionary:
                dictionary[splits[0].strip()].append(splits[1].replace('(', '').replace(')', '').strip())
            else:
                dictionary[splits[0].strip()] = [splits[1].replace('(', '').replace(')', '').strip()]
    org_factors_df = pd.DataFrame(dictionary)
    return org_factors_df
# creating a new DataFrame with the mapped factors

In [28]:
# Creating a new DataFrame from the dictionary
org_factors_df = new_columns()
# Displaying the new DataFrame
org_factors_df.head()

,Organizational rules,financial resources,organizational practices,inadequate human resources
0,yes,yes,yes,No Answer
1,yes,yes,yes,no
2,No Answer,No Answer,yes,yes
3,yes,No Answer,No Answer,yes
4,No Answer,No Answer,No Answer,yes

# merging the organizational df to the online form df

In [130]:
df_online = df.merge(org_factors_df, left_index=True, right_index=True, how = 'outer')
df_online.head()

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation,Organizational rules,financial resources,organizational practices,inadequate human resources
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,Neither Agree or Disagree,DIsagree,Agree,disagree,2.0,agree,yes,yes,yes,No Answer
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,Agree,DIsagree,strongly agree,disagree,5.0,strongly agree,yes,yes,yes,no
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,Agree,Strongly disagree,Agree,disagree,0.0,neither Agree or disagree,No Answer,No Answer,yes,yes
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,5.0,strongly agree,yes,No Answer,No Answer,yes
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,2.0,strongly agree,No Answer,No Answer,No Answer,yes

In [131]:
# dropping the original column
df_online.drop(columns=['organisational_factors_influence'], inplace=True)

In [132]:
df_2.head()

,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,network_connectivity_challenge,...,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,2025-08-21 22:09:23.948,25,Female,Degree,Doctor,O&G,NaN,EMR,Online,Always,...,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0
1,2025-08-21 22:12:37.611,23,Female,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,...,No,No,3.0,3.0,3.0,2.0,4.0,3.0,3.0,3.0
2,2025-08-21 22:15:26.993,37,Female,Postgraduate,Doctor,Family Medicine,Yes,NaN,Online,Most of the time,...,No,Yes,3.0,3.0,3.0,NaN,3.0,3.0,3.0,3.0
3,2025-08-21 22:18:44.464,25,Male,Postgraduate,Doctor,O&G,Yes,NaN,Offline,Sometimes,...,Yes,Yes,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0
4,2025-08-21 22:21:01.081,26,Male,Degree,Doctor,O&G,Yes,NaN,Online,Most of the time,...,No,No,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0

In [133]:
len(df_online.columns.tolist())

45

In [134]:
len(df_2.columns.tolist())

45

# Next steps to standardize the data columns so they can be merged and immediately analyzed

In [135]:
# cleanng for the online data:

df_online.head()

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation,Organizational rules,financial resources,organizational practices,inadequate human resources
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,Neither Agree or Disagree,DIsagree,Agree,disagree,2.0,agree,yes,yes,yes,No Answer
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,Agree,DIsagree,strongly agree,disagree,5.0,strongly agree,yes,yes,yes,no
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,Agree,Strongly disagree,Agree,disagree,0.0,neither Agree or disagree,No Answer,No Answer,yes,yes
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,5.0,strongly agree,yes,No Answer,No Answer,yes
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,2.0,strongly agree,No Answer,No Answer,No Answer,yes

In [136]:
df_online.drop(columns=['S/N','time'], inplace=True)

In [137]:
df_online.rename(columns={'13. is there a designated person to compile EHIS reports ?\n': 'designated_person_ehis_reports'}, inplace = True)

In [138]:
df_online.describe().iloc[:,:20]

       data_collection_monitoring
count                   78.000000
mean                     2.282051
std                      1.103683
min                      0.000000
25%                      2.000000
50%                      2.000000
75%                      2.000000
max                      5.000000

In [139]:
df_online.describe().iloc[:,20:]

Empty DataFrame
Columns: []
Index: [count, mean, std, min, 25%, 50%, 75%, max]

In [140]:
df_online.iloc[:10,20:]

,emr_is_complex,need_technical_support,good_system_functions_integration,confidence_using_system,used_emr_decision_making,capacity_decision_making,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,...,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation,Organizational rules,financial resources,organizational practices,inadequate human resources
0,Strongly Disagree,strongly disagree,agree,Agree,yes,yes,yes,yes,yes,yes,...,Neither Agree or Disagree,DIsagree,Agree,disagree,2.0,agree,yes,yes,yes,No Answer
1,Disagree,Strongly Agree,strongly agree,strongly Agree,yes,yes,yes,yes,yes,yes,...,Agree,DIsagree,strongly agree,disagree,5.0,strongly agree,yes,yes,yes,no
2,Strongly Disagree,strongly disagree,agree,Agree,no,yes,yes,yes,yes,yes,...,Agree,Strongly disagree,Agree,disagree,0.0,neither Agree or disagree,No Answer,No Answer,yes,yes
3,Strongly Disagree,Disagree,strongly agree,strongly Agree,no,no,yes,yes,yes,yes,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,5.0,strongly agree,yes,No Answer,No Answer,yes
4,Strongly Disagree,Neither Agree or Disagree,strongly agree,strongly Disagree,yes,yes,yes,yes,yes,yes,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,2.0,strongly agree,No Answer,No Answer,No Answer,yes
5,Neither Agree or Disagree,Agree,agree,Neither Agree or Disagree,yes,yes,No,yes,yes,yes,...,Strongly Agree,DIsagree,Agree,disagree,5.0,agree,yes,yes,yes,yes
6,Strongly Disagree,strongly disagree,strongly agree,strongly Agree,yes,yes,yes,yes,yes,yes,...,Strongly Agree,Strongly disagree,strongly agree,disagree,5.0,strongly agree,yes,No Answer,yes,No Answer
7,Strongly agree,strongly disagree,strongly agree,strongly Agree,yes,yes,yes,yes,yes,yes,...,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,2.0,strongly agree,yes,yes,No Answer,No Answer
8,Strongly Disagree,Disagree,disagree,Agree,no,no,yes,yes,yes,yes,...,Agree,Agree,Agree,strongly disagree,2.0,agree,yes,No Answer,No Answer,No Answer
9,Strongly Disagree,strongly disagree,strongly agree,strongly Agree,yes,yes,yes,no,yes,yes,...,Agree,Strongly disagree,strongly agree,strongly disagree,4.0,agree,yes,yes,yes,yes

In [141]:
column_list = ['likely to use_emr', 'emr_is_complex', 'need_technical_support', 'good_system_functions_integration', 'confidence_using_system', 'emr_performance_monitoring']
for col in column_list:
    print(df_online[col].unique())
    print()

['Agree ' 'strongly disagree ' 'strongly Agree  '
 'Neither Agree or Disagree ' 'strongly disagree  | strongly Agree  ']

['Strongly Disagree ' 'Disagree' 'Neither Agree or Disagree '
 'Strongly agree ' 'Agree  | Disagree' 'Agree ']

['strongly disagree ' 'Strongly Agree ' 'Disagree '
 'Neither Agree or Disagree ' 'Agree ']

['agree' 'strongly agree ' 'disagree' 'strongly disagree'
 'neither Agree or disagree']

['Agree ' 'strongly Agree ' 'strongly Disagree '
 'Neither Agree or Disagree ' 'Disagree ']

['Agree' 'Neither Agree or Disagree ' 'Strongly Agree' 'Disagree'
 'Strongly disagree ']

In [142]:
# Define a mapping for the Likert scale where:
# "strongly disagree" -> 1, "disagree" -> 2, "neither agree or disagree" -> 3,
# "agree" -> 4, "strongly agree" -> 5
likert_mapping = {
    "strongly disagree": 1,
    "disagree": 2,
    "neither agree or disagree": 3,
    "agree": 4,
    "strongly agree": 5
}

column_list = [
    'likely to use_emr',
    'emr_is_complex',
    'need_technical_support',
    'good_system_functions_integration',
    'confidence_using_system',
    'emr_performance_monitoring'
]

for col in column_list:
    # Clean the column: trim spaces and convert to lowercase for consistency
    df_online[col] = df_online[col].str.lower().str.strip()
    
    # Create a new column with ordinal scores
    df_online[col] = df_online[col].map(likert_mapping)

# Check one of the score columns to see the changes
print(df_online['likely to use_emr'].head())

0    4.0
1    1.0
2    5.0
3    5.0
4    1.0
Name: likely to use_emr, dtype: float64

In [144]:
df_online.iloc[:10,15:25]

,hprs_training_topic,hprs_training_provider,emr_software_rating,technical_support_time,likely to use_emr,emr_is_complex,need_technical_support,good_system_functions_integration,confidence_using_system,used_emr_decision_making
0,None (others),Nil (others),Easy to use,within 24 hours,4.0,1.0,1,4,4,yes
1,Data entry,Unit/Department head,Easy to use,within 24 hours,1.0,2.0,5,5,5,yes
2,Data entry,EHIS focal person,Easy to use,within 24 hours,5.0,1.0,1,4,4,no
3,other please specify,EHIS focal person,Easy to use,within 24 hours,5.0,1.0,2,5,5,no
4,Data Analysis,Unit/Department head,Easy to use,within 24 hours,1.0,1.0,3,5,1,yes
5,Data Analysis,Unit/Department head,Easy to use,within 24 hours,1.0,3.0,4,4,3,yes
6,other please specify,other please specify,Easy to use,within 24 hours,5.0,1.0,1,5,5,yes
7,other please specify,other please specify,Easy to use,within 24 hours,5.0,5.0,1,5,5,yes
8,Data Analysis,other please specify,Easy to use,1-7days,4.0,1.0,2,2,4,no
9,Nil (others),Nil (others),Easy to use,within 24 hours,5.0,1.0,1,5,5,yes

In [147]:
column_list_2 = ['timely_completion_emr_tasks','commitment_emr_mission','tediousness_emr_data_collection','meaningful_data_collection','data_collection_burden','data_collection_appreciation']
for col in column_list_2:
    print(df_online[col].unique())
    print()

['Neither Agree or Disagree ' 'strongly Agree ' 'Agree ' 'Disagree '
 'Strongly Disagree ' 'No Answer']

['Neither Agree or Disagree ' 'Agree ' 'Strongly Agree ' 'Disagree '
 'strongly Disagree ' 'No Answer']

['DIsagree' 'Strongly disagree ' 'Agree ' 'Neither Agree or disagree'
 'No Answer' 'Strongly Agree ']

['Agree' 'strongly agree ' 'neither Agree or disagree ' 'disagree '
 'No Answer' 'strongly disagree ' 'Agree | disagree ']

['disagree ' 'strongly disagree ' 'agree ' 'neither Agree or disagree '
 'strongly agree ' 'No Answer']

['agree ' 'strongly agree ' 'neither Agree or disagree ' 'disagree '
 'strongly disagree ' 'No Answer']

In [148]:
likert_mapping_2 = {
    "strongly disagree": 1,
    "disagree": 2,
    "neither agree or disagree": 3,
    "agree": 4,
    "strongly agree": 5,
    'No Answer': np.nan
}

for col in column_list_2:
    # Clean the column: trim spaces and convert to lowercase for consistency
    df_online[col] = df_online[col].str.lower().str.strip()
    
    # Create a new column with ordinal scores
    df_online[col] = df_online[col].map(likert_mapping_2)

# Check one of the score columns to see the changes
print(df_online['commitment_emr_mission'].head())

0    3.0
1    4.0
2    4.0
3    5.0
4    5.0
Name: commitment_emr_mission, dtype: float64

In [149]:
df_online.iloc[:10,25:]

,capacity_decision_making,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation,Organizational rules,financial resources,organizational practices,inadequate human resources
0,yes,yes,yes,yes,yes,yes,4,3.0,3.0,2.0,4.0,2.0,2.0,4.0,yes,yes,yes,No Answer
1,yes,yes,yes,yes,yes,no,4,5.0,4.0,2.0,5.0,2.0,5.0,5.0,yes,yes,yes,no
2,yes,yes,yes,yes,yes,no,3,4.0,4.0,1.0,4.0,2.0,0.0,3.0,No Answer,No Answer,yes,yes
3,no,yes,yes,yes,yes,yes,4,5.0,5.0,1.0,5.0,1.0,5.0,5.0,yes,No Answer,No Answer,yes
4,yes,yes,yes,yes,yes,yes,5,5.0,5.0,1.0,5.0,1.0,2.0,5.0,No Answer,No Answer,No Answer,yes
5,yes,No,yes,yes,yes,yes,4,4.0,5.0,2.0,4.0,2.0,5.0,4.0,yes,yes,yes,yes
6,yes,yes,yes,yes,yes,yes,5,5.0,5.0,1.0,5.0,2.0,5.0,5.0,yes,No Answer,yes,No Answer
7,yes,yes,yes,yes,yes,yes,5,5.0,5.0,1.0,5.0,1.0,2.0,5.0,yes,yes,No Answer,No Answer
8,no,yes,yes,yes,yes,yes,4,4.0,4.0,4.0,4.0,1.0,2.0,4.0,yes,No Answer,No Answer,No Answer
9,yes,yes,no,yes,yes,yes,5,4.0,4.0,1.0,5.0,1.0,4.0,4.0,yes,yes,yes,yes

In [150]:
df_2.iloc[:10,25:]

,used_emr_decision_making,capacity_decision_making,Organizational rules,financial resources,organizational practices,inadequate human resources,poor leadership,regular_monitoring_evaluation_supervisor,health_information_policies,action_plan_emr,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,Yes,Yes,Yes,Yes,Yes,No,No,No,Yes,No,No,Yes,3.0,3.0,3.0,4.0,4.0,3.0,3.0,3.0
1,No,Yes,No,No,Yes,No,No,No,No,No,No,No,3.0,3.0,3.0,2.0,4.0,3.0,3.0,3.0
2,No,No,No,Yes,No,Yes,No,No,Yes,No,No,Yes,3.0,3.0,3.0,NaN,3.0,3.0,3.0,3.0
3,No,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,Yes,Yes,Yes,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0
4,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,No,No,4.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0
5,NaN,Yes,Yes,Yes,Yes,No,No,No,No,No,No,No,3.0,3.0,3.0,2.0,4.0,2.0,3.0,4.0
6,No,Yes,Yes,Yes,Yes,Yes,NaN,Yes,No,No,No,No,5.0,4.0,4.0,4.0,4.0,2.0,2.0,4.0
7,Yes,Yes,Yes,NaN,NaN,NaN,NaN,Yes,Yes,Yes,No,Yes,3.0,3.0,4.0,1.0,5.0,1.0,4.0,4.0
8,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,4.0,4.0,4.0,2.0,4.0,2.0,4.0,4.0
9,Yes,Yes,Yes,NaN,Yes,No,NaN,No,Yes,Yes,Yes,No,3.0,3.0,3.0,1.0,5.0,4.0,5.0,4.0