##  Importing the packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_excel('EMR analysis online.xlsx')

In [4]:
df = pd.DataFrame(data)
df.head()

,S.NO,Submitted Time,1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS,2. SEX,3. LEVEL OF EDUCATION,4. Profession,5. Name of clinic,6. SECTION TWO : TECHNICAL FACTORS,7. what is Database version,8. Is EMR online /offline,...,31. Does your facility have a regular meetings to improve the EMR utilization?,32. Have you received regular feedback on your report ?,"33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n",34. facility staff complete EMR tasks in a timely manners (i.e meet deadlines ),"35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data","36. SECTION FOUR : BEHAVIOURAL FACTOR\n PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE",37. collecting data is meaningful/useful work for me,38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties,39. collecting information gives me the feeling that data is needed for monitoring facility performance,40. my work of collecting data is appreciated and valued by superiors
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [5]:
df.set_index('S.NO', inplace=True)

In [6]:
df.reset_index(inplace=True)

In [7]:
df.head()

,S.NO,Submitted Time,1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS,2. SEX,3. LEVEL OF EDUCATION,4. Profession,5. Name of clinic,6. SECTION TWO : TECHNICAL FACTORS,7. what is Database version,8. Is EMR online /offline,...,31. Does your facility have a regular meetings to improve the EMR utilization?,32. Have you received regular feedback on your report ?,"33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n",34. facility staff complete EMR tasks in a timely manners (i.e meet deadlines ),"35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data","36. SECTION FOUR : BEHAVIOURAL FACTOR\n PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE",37. collecting data is meaningful/useful work for me,38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties,39. collecting information gives me the feeling that data is needed for monitoring facility performance,40. my work of collecting data is appreciated and valued by superiors
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [8]:
df.columns

Index(['S.NO', 'Submitted Time',
       '1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS ', '2. SEX ',
       '3. LEVEL OF EDUCATION ', '4. Profession', '5. Name of clinic ',
       '6. SECTION TWO : TECHNICAL FACTORS ', '7. what is Database version  ',
       '8. Is EMR  online /offline ',
       '9. Is network connectivity a challenge?',
       '10. if yes ,what alternative do you have when there is no power ',
       '11. Is there a designated person to enter patient data upon registration in the health facility?',
       '12. How are patient registered upon arrival at the health facility?',
       '13. is there a designated person to compile EHIS reports ?\n',
       '14. Do you take orientation on the EMR   utilization upon employment?',
       '15. have you attended training on the Health Patient Registration System (HPRS) in the last 12 months ?',
       '16. if your answer is yes for question number 15 ,which topic did you train ?',
       '17. if your answer is yes for question number 15,who provides the training?',
       '18.          How do you classify/rate the EMR  software based on your experience ',
       '19. The following questions refer to the             computer/s used for EMR .\n\nHow long does it take to get technical support after an assistant call is logged ?',
       '20. For the following questions please express your level of agreement using the likert scale;',
       '21. For the following questions please express your level of agreement using the likert scale;',
       '22. I think that I need the support of a technical person to be able to use the system ',
       '23. I found the various functions of the system to be well integrated ',
       '24. I felt  very confident using the system ',
       '25. SECTION THREE: ORGANISATIONAL FACTOR ',
       '26. Do you have the capacity to make decisions relating to your responsibility ',
       '27. which organizational factor/s influence information use in your facility (You can choose more than one answer)',
       '28. does your facility have regular monitoring and evaluation supervisor for EMR ?',
       '29. Does the facility have well streamline health information policies ',
       '30. does the facility have an action plan for EMR  ?',
       '31. Does your facility have a regular meetings to improve the EMR utilization?',
       '32. Have you received regular feedback on your report ?',
       '33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n  ',
       '34. facility staff complete EMR  tasks in a timely manners (i.e meet deadlines )',
       '35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data ',
       '36. SECTION FOUR : BEHAVIOURAL FACTOR\n   PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE',
       '37. collecting data is meaningful/useful work for me ',
       '38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties ',
       '39. collecting information gives me the feeling that data is needed for monitoring facility performance ',
       '40. my work of collecting data is appreciated and valued by superiors '],
      dtype='object')

In [9]:
# Mapping for new column names

mapping = {
    'S.NO': 'S/N',
    'Submitted Time' : 'time',
    '1. SECTION ONE :SOCIO DEMOGRAPHIC RELATED QUESTIONS ':'Age',
    '2. SEX ' : 'sex',
    '3. LEVEL OF EDUCATION ': 'education',
    '4. Profession': 'profesion',
    '5. Name of clinic ': 'clinic_name/department',
    '6. SECTION TWO : TECHNICAL FACTORS ': 'EMR_designated_computer',
    '7. what is Database version  ' : 'database_version',
    '8. Is EMR  online /offline ': 'emr_online_offline',
    '9. Is network connectivity a challenge?': 'network_connectivity_challenge',
    '10. if yes ,what alternative do you have when there is no power ': 'alternative_power_outage',
    '11. Is there a designated person to enter patient data upon registration in the health facility?': 'designated_person_patient_data',
    '12. How are patient registered upon arrival at the health facility?': 'patient_registration_method',
    '13. is there a designated person to compile EHIS reports ?': 'designated_person_ehis_reports', 
    '14. Do you take orientation on the EMR   utilization upon employment?': 'orientation_emr_utilization',
    '15. have you attended training on the Health Patient Registration System (HPRS) in the last 12 months ?': 'hprs_training_last_12_months',
    '16. if your answer is yes for question number 15 ,which topic did you train ?': 'hprs_training_topic',
    '17. if your answer is yes for question number 15,who provides the training?': 'hprs_training_provider',
    '18.          How do you classify/rate the EMR  software based on your experience ': 'emr_software_rating',
    '19. The following questions refer to the             computer/s used for EMR .\n\nHow long does it take to get technical support after an assistant call is logged ?': 'technical_support_time',
    '20. For the following questions please express your level of agreement using the likert scale;': 'likely to use_emr',
    '21. For the following questions please express your level of agreement using the likert scale;': 'emr_is_complex',
    '22. I think that I need the support of a technical person to be able to use the system ': 'need_technical_support',
    '23. I found the various functions of the system to be well integrated ': 'good_system_functions_integration',
    '24. I felt  very confident using the system ': 'confidence_using_system',
    '25. SECTION THREE: ORGANISATIONAL FACTOR ': 'used_emr_decision_making',
    '26. Do you have the capacity to make decisions relating to your responsibility ': 'capacity_decision_making',
    '27. which organizational factor/s influence information use in your facility (You can choose more than one answer)': 'organisational_factors_influence',
    '28. does your facility have regular monitoring and evaluation supervisor for EMR ?': 'regular_monitoring_evaluation_supervisor',
    '29. Does the facility have well streamline health information policies ': 'health_information_policies',
    '30. does the facility have an action plan for EMR  ?': 'action_plan_emr',
    '31. Does your facility have a regular meetings to improve the EMR utilization?': 'regular_meetings_emr_utilization',
    '32. Have you received regular feedback on your report ?': 'regular_feedback_report',
    '33. please express your level of agreement using likert scale ;1 -strongly Disagree, 2-Disagree,3-Neither Agree or Disagree ,4-Agree ,strongly disagree \n\n  ': 'emr_performance_monitoring',
    '34. facility staff complete EMR  tasks in a timely manners (i.e meet deadlines )': 'timely_completion_emr_tasks',
    '35. facility staff display commitment to the EMR mission (i.e to generate and use good quality -accurate , complete and timely -data ': 'commitment_emr_mission',
    '36. SECTION FOUR : BEHAVIOURAL FACTOR\n   PLEASE EXPRESS YOUR LEVEL OF AGREEMENT USING THE LIKERT SCALE ;1 STRONGLY DISAGREE,2-DISAGREE ,3-NEITHER AGREE OR DISAGREE ,4-AGREE,5- STRONGLY AGREE': 'tediousness_emr_data_collection',
    '37. collecting data is meaningful/useful work for me ': 'meaningful_data_collection',
    '38. I feel like the data I collect burdens my workload .making it difficult for me to complete my other duties ': 'data_collection_burden',
    '39. collecting information gives me the feeling that data is needed for monitoring facility performance ': 'data_collection_monitoring',
    '40. my work of collecting data is appreciated and valued by superiors ': 'data_collection_appreciation'
}
# Renaming columns using the mapping

In [10]:
df.rename(columns=mapping, inplace=True)
# Display the first few rows of the updated DataFrame

In [11]:
df.head()

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,regular_meetings_emr_utilization,regular_feedback_report,emr_performance_monitoring,timely_completion_emr_tasks,commitment_emr_mission,tediousness_emr_data_collection,meaningful_data_collection,data_collection_burden,data_collection_monitoring,data_collection_appreciation
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,yes,yes,Agree,Neither Agree or Disagree,Neither Agree or Disagree,DIsagree,Agree,disagree,agree,agree
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,yes,no,Agree,strongly Agree,Agree,DIsagree,strongly agree,disagree,strongly disagree,strongly agree
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,yes,no,Neither Agree or Disagree,Agree,Agree,Strongly disagree,Agree,disagree,neither Agree or disagree,neither Agree or disagree
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,yes,yes,Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,strongly disagree,strongly agree
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,yes,yes,Strongly Agree,strongly Agree,Strongly Agree,Strongly disagree,strongly agree,strongly disagree,agree,strongly agree

In [12]:
df.iloc[:, :30]

,S/N,time,Age,sex,education,profesion,clinic_name/department,EMR_designated_computer,database_version,emr_online_offline,...,technical_support_time,likely to use_emr,emr_is_complex,need_technical_support,good_system_functions_integration,confidence_using_system,used_emr_decision_making,capacity_decision_making,organisational_factors_influence,regular_monitoring_evaluation_supervisor
0,1,18-06-2025 10:38:10,1967,Male,Postgraduate,Doctor,FMC Ebute metta,YES,Unknown,Online,...,within 24 hours,Agree,Strongly Disagree,strongly disagree,agree,Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,yes
1,2,18-06-2025 16:04:34,25,Female,Diploma,other please specify,Not in a clinic,YES,A database version refers to a specific iterat...,Online,...,within 24 hours,strongly disagree,Disagree,Strongly Agree,strongly agree,strongly Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,yes
2,3,19-06-2025 01:18:11,34,Female,Diploma,Nurse,PICU,YES,An update of a database management system with...,Online,...,within 24 hours,strongly Agree,Strongly Disagree,strongly disagree,agree,Agree,no,yes,Organizational rules *( No Answer )\nfinancia...,yes
3,4,19-06-2025 08:41:41,37,Female,Degree,Nurse,Immunisation/family planning clinic,YES,Information system,Online | Offline,...,within 24 hours,strongly Agree,Strongly Disagree,Disagree,strongly agree,strongly Agree,no,no,Organizational rules *( yes )\nfinancial res...,yes
4,5,19-06-2025 08:49:38,24,Female,Diploma,other please specify | Health Record Technici...,Specialist Clinic 2,YES,V10.0,Online,...,within 24 hours,strongly disagree,Strongly Disagree,Neither Agree or Disagree,strongly agree,strongly Disagree,yes,yes,Organizational rules *( No Answer )\nfinancia...,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,75,18-07-2025 13:18:23,1987 Oct 27,Female,Diploma,Facility information officer,Specialist 11,YES,1.0,Online,...,within 24 hours,Agree,Strongly Disagree,Disagree,disagree,Agree,no,yes,Organizational rules *( No Answer )\nfinancia...,yes
75,76,18-07-2025 17:48:02,44,Female,Postgraduate,Doctor,Federal Medical center Ebute-Meta,YES,EMR,Online,...,within 24 hours,strongly Agree,Disagree,Disagree,agree,strongly Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,No
76,77,19-07-2025 16:19:32,43 yers,Female,Postgraduate,Filing clerk,FMC Ebute Metta Lagos,YES,Meditech,Online,...,within 24 hours,strongly Agree,Strongly Disagree,Agree,agree,Agree,yes,yes,Organizational rules *( yes )\nfinancial res...,yes
77,78,21-07-2025 09:35:21,28,Female,Degree,Facility information officer,Federal Medical Centre,YES,10,Online,...,within 24 hours,strongly Agree,Disagree,Disagree,agree,strongly Agree,yes,yes,Organizational rules *( No Answer )\nfinancia...,yes
78,79,26-07-2025 00:26:18,52years,Female,Degree,Nurse,Paediatric,YES,Don't know,Online,...,within 24 hours,strongly Agree,Disagree,Neither Agree or Disagree,agree,strongly Agree,no,no,Organizational rules *( No Answer )\nfinancia...,yes

In [13]:
# saving the updated DataFrame to a new Excel file
df.to_excel('EMR_analysis_online_updated.xlsx', index=False)